apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: now-u
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/now-u/now-u-k8s-app-config.git
    targetRevision: HEAD
    path: causes
  destination:
    server: https://kubernetes.default.svc
    namespace: now-u

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
