namespace: now-u-prod
images:
  - name: ghcr.io/now-u/now-u-backend
    newTag: sha-b0370f7
  - name: ghcr.io/now-u/now-u-app-links
    newTag: sha-d714ca1
resources:
  - ../../base
transformers:
  - |-
    apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: fix-argo-app-namespace
    patch: '[{"op": "replace", "path": "/metadata/namespace", "value": "argocd"}, {"op": "replace", "path": "/spec/destination/namespace", "value": "now-u-prod"}]'
    target:
      kind: Application
