apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: now-u-causes-db
spec:
  instances: 3

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      destinationPath: "https://causesdbbackup.blob.core.windows.net/causesdbbackup/"
      azureCredentials:
        storageAccount:
          name: causes-db-backup-azure-secrets
          key: storage-account
        storageKey:
          name: causes-db-backup-azure-secrets
          key: storage-key
