apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-u-causes
spec:
  selector:
    matchLabels:
      app: now-u-causes
  replicas: 2
  template:
    metadata:
      labels:
        app: now-u-causes
    spec:
      containers:
      - name: now-u-backend
        image: ghcr.io/now-u/now-u-backend
        env:
        - name: DEBUG
          value: 'false'

        - name: BASE_URL
          value: https://causes.dev.apiv2.now-u.com

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: django-env
              key: jwt-secret

        - name: DJANGO_SUPERUSER_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-env
              key: superuser-email
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-env
              key: superuser-password

        - name: STATIC_FILES_STORAGE_CONTAINER
          value: cs-static-storage
        - name: STATIC_FILES_STORAGE_ACCOUNT_NAME
          value: csstatic71effcce
        - name: STATIC_FILES_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: static-files-secrets
              key: account-key
        - name: STATIC_FILES_STORAGE_DOMAIN
          value: csstatic.azureedge.net

        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: now-u-causes-db-app
              key: dbname
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: now-u-causes-db-app
              key: host
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: now-u-causes-db-app
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: now-u-causes-db-app
              key: password
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: now-u-causes-db-app
              key: port

        - name: MAILCHIMP_LIST_ID
          value: b604a851dc
        - name: MAILCHIMP_SERVER
          value: us4
        - name: MAILCHIMP_API_KEY
          valueFrom:
            secretKeyRef:
              name: mailchimp-secrets
              key: api-key
        - name: MEILISEARCH_URL
          value: "http://meilisearch.now-u-prod.svc.cluster.local:7700"
        - name: MEILISEARCH_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: meilisearch-secrets
              key: MEILI_MASTER_KEY

        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: key

        ports:
        - containerPort: 5000
          name: http-svc
---
apiVersion: v1
kind: Service
metadata:
  name: now-u-causes
  labels:
    app: now-u-causes
spec:
  ports:
  - name: now-u-causes-svc-port
    protocol: TCP
    port: 80
    targetPort: http-svc
  selector:
    app: now-u-causes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: now-u-causes-ingress
  annotations:
     cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - causes.dev.apiv2.now-u.com
    secretName: now-u-causes-ingress-tls
  rules:
  - host: causes.dev.apiv2.now-u.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: now-u-causes
            port:
              number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: now-u-causes-search-sync
spec:
  # 4am every day
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: now-u-causes-search-sync
        spec:
          restartPolicy: OnFailure
          containers:
            - name: now-u-backend
              image: ghcr.io/now-u/now-u-backend
              command:
                - /bin/sh
                - -c
                - date; echo Starting sync && ./manage.py populateMeilisearchIndex && echo Sync Complete
              # TODO We shouldn't be copying this container spec
              env:
              - name: DEBUG
                value: 'false'

              - name: BASE_URL
                value: https://causes.dev.apiv2.now-u.com

              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: django-env
                    key: jwt-secret

              - name: DJANGO_SUPERUSER_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: django-env
                    key: superuser-email
              - name: DJANGO_SUPERUSER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: django-env
                    key: superuser-password

              - name: STATIC_FILES_STORAGE_CONTAINER
                value: cs-static-storage
              - name: STATIC_FILES_STORAGE_ACCOUNT_NAME
                value: csstatic71effcce
              - name: STATIC_FILES_STORAGE_ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: static-files-secrets
                    key: account-key
              - name: STATIC_FILES_STORAGE_DOMAIN
                value: csstatic.azureedge.net

              - name: DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: now-u-causes-db-app
                    key: dbname
              - name: DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: now-u-causes-db-app
                    key: host
              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: now-u-causes-db-app
                    key: user
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: now-u-causes-db-app
                    key: password
              - name: DATABASE_PORT
                valueFrom:
                  secretKeyRef:
                    name: now-u-causes-db-app
                    key: port

              - name: MAILCHIMP_LIST_ID
                value: b604a851dc
              - name: MAILCHIMP_SERVER
                value: us4
              - name: MAILCHIMP_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: mailchimp-secrets
                    key: api-key
              - name: MEILISEARCH_URL
                value: "http://meilisearch.now-u-prod.svc.cluster.local:7700"
              - name: MEILISEARCH_MASTER_KEY
                valueFrom:
                  secretKeyRef:
                    name: meilisearch-secrets
                    key: MEILI_MASTER_KEY

              - name: SUPABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: supabase-secrets
                    key: url
              - name: SUPABASE_KEY
                valueFrom:
                  secretKeyRef:
                    name: supabase-secrets
                    key: key

