apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: now-u
resources:
  - adminer.yaml
  - db.yaml
  - deployment.yaml
  - sealed-causes-db-backup-azure-secrets.yaml
  - sealed-django-secrets.yaml
  - sealed-django-static-files-secret.yaml
  - sealed-mailchimp-secrets.yaml
  - sealed-meilisearch-secrets.yaml
  - sealed-supabase-secrets.yaml
  - search-ingress.yaml
  - search.yaml
  - app-links/db.yaml
  - app-links/deployment.yaml
  - app-links/sealed-app-links-secrets.yaml
