---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: static-files-secrets
spec:
  encryptedData:
    account-key: AgAdGkPK9TcW/uVO29ZhFJwxL7DSLFNbWdRadFEuJsv6v5NoJvgDCWUnlRYIvk3C+fjUUVamSUKneWMTmMPcMkLZiTXSm2+ARJl2rUUO/o/+jxz/m0Qc3hLOLJ/VZ0XUDDjU0ZDtFuUXnzYdHSO9qzhZ3J8ub62g0Nt01cN/bb8aBvEHVQYdhOIxBIsJFE41KLu0e9hdnIpJz4kcjnU6rF35mrXq2ka/q6n6PctghsX4A3PDzNUmLyTXJAhV8zUh/8NL2pIp9Rb+no992wakjJsyITYAx3qqADvncdd12rs/zH4biluJLomoEfBI7/YHH3F4BvIbwAlJG6F8NCxfmUxz3A+I+3r5yDALY3lEFRQ/rNRX0BV07eSiqGm4zxNCfebHdKcXDx6lhH7/mVnYTj5dbrt3BxiR9ypkKtR2kf9lYfWiEzg1coAwFgqOXuOJr4RrSwGj9Y1sRnjmAaNydzq2+40+N+hBbj0KkO5L+wcxcaHhVPeREjTeFL7yQYCB/js3b04JQTvpHIEiivHmMIfBHMQ5KJdUza7tvA8P4tQiDvDvtmPmXPHEX8xn75TWGdzsDt/6vZ27rt8rjg4vJjnUHUjWLvchG69tyaCABcGxIgZXm2fidXbTCGCpOKGrzrkERl5CBCz3VxdWXpSuv+m4MHzjVhfTSNoofPt/kGv405oO3K0Esi8gljKD0Z9om3Cg34/OZEF/YsbSFt1TWyRSIptRK3rz/gEBciz1GBw2dcPmseSZ3Rt7EY1tmmNrDzneIauUZ9KrTz1IeNvJbWnBHwDBuc4HaWaBdCKIjVDEuJAHn7p1tTMR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: static-files-secrets
