---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: meilisearch-secrets
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBOeEW79CQs1+HvJV2/oHXoSIlTX2Z5/bCfCkkDOU9/mpkPiVjw8JXc+mhPHOG9lC+El9+x0f0njstyB/d4QWAyGbCCHjwhlcCi5QRs8X6VT4zNc7yBZYAdlyhQ2lqkPsPbYe1ENaCCC4eyqRSe4SKwrARkqako88pUqCTsQZ/lRUAP9GGvJIbNAuVTuuP7hLqj2kA0JmnAjGb1PSGqcb/wtWn/Q91Onrj/JGeDWxr1LpajmIPh3yGb7JnehkCgEnjBbZTe8MbzU640BsUOBJ+A3OkUat0tvw7FJ6KIQvI9k/3HmOGSPLPi7fNUl71UC2XHx/Cb8hy/FDAe8piKie8+G5rhpeTLu8CNyw+czxfFy+iuv5AXGcpHLn0urNEQFzgEg9t5Ff5dLYOVYCJCY45t7cXGUUilgfL4Dip4v1ausV8/ufhzuXlKi8X9Kl4E/OixnwifmCCf9GUhQgbsXIs8pBh9VAmjmzfqMnxGLpysJBgeOjiQW7GYtFRGdZbXv9nedueSUtq1DGa5ShY7b8UNKyHw6JwUAI99tVgr68m/cp13lDsvfD7rijea01eBp/EnwgSqFU/+KDIgiVa6mT/olYkQN+isrCuFtyfkAmVDgC3pwI+fVlS2IMVlrc+JsTwGruP97RH3Jfdd5ghrX9+TQjaVds3MV3V2SHCxKXYyiFGggWbeDNYJAYFLr7V56M1csp7FwHThfgTRNDLrRRag4xkuOiiCkCQZDhe7B6+aTw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: meilisearch-secrets
