---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: meilisearch-secrets
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgC4TLcFMFeq3iqCSwJLCZb8g0LsLrGS5W03X0MvyaAA4kopvKWO5bK5+x98b9k3tM0n0aY2vIrBOE7DilpoW2bGvdmQQzA+5XeSCWYu1Z3v3c57JvuEDMSU6noUSp7wngU/n0A/ZvbsLlyeasiZSoDs4FnJvo7h0SurtvCQ96HP8Hy6Uj7oKhBR0LtW3CkXPTgPK0uD/l3BBFopmR70lfga9EbI28Gf5VKD1wdDO59KsI3FcDPqT/5e3s25xR6K/wflYGKFhnfqB+GBNAlrM2lkr7ygoHMR9RUNQpsBc0N1EjtSg3FzPBy2bbdIpouu8fhGfvgsR78FEAAz9f6axIXVy0ll9yeHvyLjahT7mLJ4SeXfNJcBtF3iv4vuyb+guGd5+9XgexblA8riertWaAVzoQl5sJyZd1J44D3s66xDZUCDi4iNzRjzD6VGjT7UAmP/2I/mfauXVOzpBawD8ejGtNDdu8V4ECa+mUado/USUoDCE0R4MurM3ZDsB4ZWl0ixIErCwKvhzJ+imWm+GGgw5rgZal5MDV0m8zFM/GOH32krn6e4Zg8k6U9eLNVZXYEX3PHwAUMJbhZvz5CXrB9hp1polp2ckICH3uykR8a7zj7IUyB+xNY2wTtrlj0e00hg8fripymEMjvE2uS8718mee0TBCnDR3iGnX4ilxtCYOMDB8zZr9fNo2i1G3cPm4VBFz5ZOZmHIkKX4qX+32j45RdIdI6QPMPc0Pcr/sKBMA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: meilisearch-secrets
