---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: causes-db-backup-azure-secrets
spec:
  encryptedData:
    storage-account: AgCVrUhkt+QX7UCkQ+k6Pb28/VKLXEkHuzyL2jIWVIYh7OzgrKuwBKl5QGICKJngFDDmoeJux1mDpXYv+7tu7Oycco3Z1jImpl0vaj75klmZuwfHp/EYBtp8c2apZickSpwYWxilj+ZlhcsFuMTPU9Tg/qIizRmZgWjqzdYtvUD6KRW+BJJ7cGEEKwnFISxIGLb0htR5rPC5sae69Zl+coFNosrfdbF37IxdRTu7oQzECY8clotq72Noqit5jbU1TMPDhv6TT4HFoXBdx55sQ3nLGf5x1NdocXInwMMo1cHwUQDlQXHgbokZco7YnabVx4V0726P4AjMJTC7kP7WZcogqqZy7rr4dASrLF9vORekXxYgVh3anJ3uctY9UEUMdoqbkPK3/e/2efohdGcylP6Gn9t26ad8BFJ1nvxYlbBlehuzJ2+CU0/EE6kXy48gAapExcoi3l/hjyIGiNPEgFpmRQg8Zpc8KBOol5riGbbIAMMtvWS2tXpBm4GjTBdX43/kjf29R5p8bgihZQvon61DPDGojWZM5w/5/f1S1OF1YDVv4fYg1uYRxp+Bi7FRfVYglYbhgsROeDFtlVpXAxb3EPV3AcvZrh9lGVozEg8BLAw3pwQMKyRxkchPuBXRfSY1b8d0d/MMdF12G00Fa1SUWuveVYBrLjaUCNZ9WQjDp2nl0Ybz0gY5Znc03oUhyXNPHGml1OByw5w+d+yxAw==
    storage-key: AgBZpTvrARyGk8B+flET1V9ug5EJ/9GKU3OW+l5dLgzrDwif+HLt+bMf4h32rGk2FaSolbemmoQMNoS3nH4wZqtmnvdIFVUaa4qb60JY22qNO1hoihszYswXrnV7140ThxC3iKkYeDQqqff7WX3x13waClXuxQTzKtfaTdZfzE/j9hMA1JFX72Qv/8xsdostwGS1zV9p7ByFVvyu69zioCb0fkWlAzJIPkUfbzBz4u+1N9GptECK1QjLBHVWhVb7fLbcGI4BlFasGFEzwS+8upUfJFWYo67jypFjmNnilQiXvh/pzaa2Rl7v4rlxuc3ticOQ06qvXiT/iIdtoG+SJBAiwv5zqdswxKX5Qpfy9TuyY+Q7Q8Tqiw8idGKnJn9iyYFK4E3ufVczJnFtZodvpVSpbMUnj1A6at1NL8+y//I5WvaVxUwDD4L0e4sAYw2JuFA06LryxTYifH/d2CIvKkulEEPeoCvxkRuAUvxc7C6Yu20VMTA0XXNxrv4QTiucfM8nejPGVwOFmCZHrK+2JFrh9cR7iVqEStztTQCBtW48mHRDcgcVEN+LliStFK8sAPAP1Iv0WtVhr/JweNRwaWSkiab76UhSPB9aPiBRcuJQ0EshuwcO/lgl0ZJ4ihUpStQNUK1Rc+xmM8Y/UMtqBbDvgRlVCLCQYuflJ7S6Tb8fhGi40gU6wPZChHYzx0r3Z5PIibUSmjGu6rMGa5YrE3M+voEPsM0SsHimtm8lQtMoqj+Oqvbnb0a7uQQRhBzNdKxu3ES0XoCR9wbpEWjcvnaUmG2HJ7uRFmBQut8yeX8XDpGgPLiw6Dbk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: causes-db-backup-azure-secrets
