---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: static-files-secrets
spec:
  encryptedData:
    account-key: AgCmU8m+8BKHvm+TEjZ4E5UwFlF1tjyqwl1lplF5/zBv7ViEdrKC6K/OOqTqiHYjjYkvcHn1b5MgOg93rT9Dwp9dXOCqX84zTNj1kBbaPToWzDykVrMHl+x5YeBjLgcF9O++kdl1yyq1opfsacxgnnTCofZmoDMQlpu64V2fLSzcOnsaxablE3N0ozSTf2hGZL9sG7ySlrYmTeOhHQ/6uT0xgG9EuoFJH1BjILvZ10RkOUwHPkVwghv1x1ZyyvX0O4YTOsJulTAJ48zLKaDf7tn2woy66BuReiN9Ez8wosO2PGHqxilbpMqptXwkPp0jSSRL/YFzXF59qoJkjo8zRhCITq9QhwzPiYhsGFKZIe/UJFN/tJ8C034kdVJ7DOt6U7NCMcoBAY3ztU3N8ty6aDMzf9a+SrEufvBSACx8il3ausZ7PaiZrjeSYqFM/TblHNj+0HLctyi1WKW/N5MXQ7+5daMWTPqBUFsu3vcchzeF8lyBvVxuH9WQW/XVO2WY6vHrP3IjcdRi733d1DhbVLDHj9ONK2TeLF63IUYkKtMRJoIDfmEHEKJqENzuqWOLynV3vK2V1cPp9Yi6M/XMZ7fWrm0bU70Mf7ZD4uFIRjxAy78ZBB83ZJAU74eZp4twIdEoskz5KcyCPcWJtZaVaXL58iHeLBhXONwDH94o3gY15qUJX+GgI9GqBJB3CAjPNrqjnwmyOXmkNreJc/lHSx1yfLqjF0o6e7I+tSNGXsf+juVp2pFBC0kWGs1VIqZ49ptIffmppez3Fza+8PSqmDOwTxU+ONdVcF3wh0hh4M13gFCfuzwKTJM3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: static-files-secrets
