---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mailchimp-secrets
spec:
  encryptedData:
    api-key: AgAjGqyOneRAyGkN7RlivxgplFKVwthCfR9Fzhs04Md5zUvHaBYEHwNy05bRi/IjiFzf06P2jAbBXBYUncCUpoW95a5eZSlhZuzSzpCu4dHJ/wy+QOnw5OlBPkxbAw7QPWifgLhudg1TDT99edvGaaCBumv0P0qo/UCSABik4U6Go9Pqlv2rPXoaBgGKkLzmVvqWrY3CoX93pNz6XdBseLkw4nmx+fOamT8f+ATsSnOjKYlY8pG3U16YoeMcVXfp4pBzz/Tjt3P48SmcAVbLRnaVyozEpS3zdGmSB3crTf/MpKpZy8+mQ3YBKCApm4OtPIwa7eMmuXsHK0aSbI/odPmbPHH5CemhhlaS8yqHSe0Uirtdgw0FmFp51B9iEV+whwKPsy+DzB073gEu4hDjwstiDwwsLQHyUwnqSGBe99UsWcqEVOPcerhcqFfG6KRx+0bLYFQEZIaHzAvf5kE/roS2Vwvcj6tosUr5n3uw1jvvsh9bM6RTdFOiNJLC8otyk53yttgZw/Zd2vL0ZuyiGjH5MG/tXbNtLPloz1sMykSF1MEbuQSId5ZIkVdR7aFXse2dnR9JeIv5BO1mAYs6uhuTwLFDwAy8xhP2oKP2Vg1KkyCrkOPS1BjOj9ORy2B79OtADyKug0odApY6pmbo7JtCIA0mwDKQW/c/pTZ5lh0Jq7lXY+R12eRpgkFnHt5zqwrt2GlIPZsFraS3xU0g4K6okQ72GjMwwTBxw2MeJXvhGa1o2h4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mailchimp-secrets
