---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mailchimp-secrets
spec:
  encryptedData:
    api-key: AgAQb/0i5aIG82lMTcWAbelNsWrjIfI3p/ssxrBzlq6ERGgDQecwwNUal8gSQcMVDqi++uhvptrv8jtUU8s4tptKwQTh/qkr+U02TdeR/sPxrACv7t3FlGFLA81mtgXECl1Bb9Zvk1eeUu2CZgJLpF9cvF4YDYMcjkycWiRUVR8y7wcECdoJl9UN2HLfIRZrQHCkmP2CjR2nYFOFFfXssKmuo7HrF3PtSZfqgWByVD7VsiPgJRh/owaSn3Kn+XC23+VX1Wueacga2ntemqRUkMuLhz4uMW+QmXh9s2LHQihv1+BGtZw2OOeiKQeg6GWflsof8rRF4dJ0FPxfMsswu8yxUoR1238BbMi860Y8FPQpddoWFzTN08hSa/Wii0VUT6hDkJ5XG4vmTG6FdlA9iatZW3ntumZX1pHoUK1QbldOaVdOgTsRTnjGFwzMaJZxOdTKLkxLjZeCdcjxkKXKZPHy8XHpiCMtqjfP7aAzCpIlc9qJWYGIyW2XFXmUJWx3nmpldokjTG8a0B7s8HoMz6JBPe7X1jaDVrJ69kApwnxPxUqzDlRu8lL9RmjUzH+ZOWM8c8eE0IVcxl897SuCcDIQ7SAOy0ynV4G7ZOZZ8gCoMA0NRzJvtwbU2NF9f1ZM1M1G+X3cnmppwshD0sPaJolHQzKjSIthx0k1dfxLoS521ouIC0glpi7UfrJ48jnU23OTHeqmIrIW+MCu79Psae2KBGwr+FaysaQ8SB5ep9WYapybrvg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mailchimp-secrets
