apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meilisearch
  namespace: argocd
spec:
  project: default
  source:
    chart: meilisearch
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    targetRevision: 0.6.1
    helm:
      releaseName: meilisearch
      valuesObject:
        auth:
          existingMasterKeySecret: meilisearch-secrets
        persistence:
          enabled: true
          storageClass: microk8s-hostpath
          size: 2Gi
        serviceMonitor:
          enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: now-u-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
