---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: app-links-secrets
spec:
  encryptedData:
    api-key: AgAlcYfnUeCv8Em5ItClpy/gJjNc5GCkfjYhJcKx6uHwVxfKvB3ypz1ktWW0R22fxO5uq95nMxnEY1+CWh0P5JmBEVezcaUFBildjWITRMIPlN/FEld06endFek1tzyUD1VWjghSyiclrU4ccuBEoZhJzxAewVtK3FMzPteYNZO7OZdFF1hNPPT4exDijOXYmvkf4uFxKNBjARNCk99I83ynbcVtSFH5tYGhbUxVpCA3bzGxB2QVflVy/yF5DMMLMhhBztPutv3+tM10b3QgN7ecLk4abemg0F/5ZjBcVQ9vZHmJUvKAVA7p9fDvKCM0wmqWNxmz8suD3fla4//92XipfDco6LF7TuGHNzWJWa+TOFXx2UwGLzy7mj/L3cOnw6Kp6TysjqD9ar1BrLeWkyUlAmCpctEk/ZvkZuohJJMwTOQL4IXDe6/j1pPxRt2lXL0vayg7otfD56FHFrIMtz1a4a8E83Nyqi/MEV2OdHRKAvct1C4t2NVZn+acejrKpOdWC4dv6vOGUIivsip5VIaXgGO8Qtd7Mr5jlpGfmniv9IkSAH/3SF4BTOPaJ320q2yyYdXE2OSTwuQJxgALLz6ujrYHaSfnrJGryflfhUwL4pQfMeKlm1kCC756QUCplCVGZMh4qR+VY9A++5JqGRU6XieAJyPHu3ENPuHgSm7pNJ1+IrXQO3kX2UsaWbLToWK/vE3hCi4lPz68uiTW5YcUJg36ouGqBUWvDsp/kR0ucL3n6H7cenUTAmVu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: app-links-secrets
