apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: now-u-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/now-u/now-u-backend, ghcr.io/now-u/now-u-app-links
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/now-u/now-u-k8s-app-config.git
    targetRevision: HEAD
    path: now-u/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: now-u-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
