---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: causes-db-backup-azure-secrets
  namespace: now-u
spec:
  encryptedData:
    storage-account: AgA2NrbbCIw3YMIO5BJ0fhnc2jZBbv5D9LfTH4lHM1KLB4R81EM6DmWDTKqte9Xg3PnqDLupGoQmVNywZ8gtBxUYEdNxqsFsvk5XwCR64+tAduqD0avnDcL96jX2L7iFHUHNr4OBRqqrSh/B54TiCLtuP4cltPnX23RMq0QDOITbG7EDlJdZoxSA5Fe1lDoQAGxz8M+aeBBsaobklMKheKqrzqLMhwjk8D3eVjp1l2qA19qQX4l/sBSVHGT79kZxsEfEZLw5KI3u2G4B9Y3hPSnIx5grgBH3fZMHiNRPGc5AEjXcpPovwBEYWlXcjT++JkiqjPyiSJU24LpJ+zPli5wt6mVUd+R2ofjR5QND30sL/l24KpJbYXuIAZ+hiOMtLedVwz3DnV6JXCOToQ6U2mXypYH/cKpOkb7zbVIzBJ+/m+CVHKLIGyppR081zmtzLPjVPoLDoGbTbQp+CpRCLCmZNyzdEwkaxTtxH+LP9N1L5DW/9a7R8rZzxOG7KdAEnD5PxSru/DZgJAqBZdpGzDLNfMk2S41T3rfrsL16lXfQQ287R/IGcgZ+ES2mJ+bNlGtzcfqdPJkdc+2TjdLznT9HrxtH0fGoqadtNJ3lm5spAUhs2G0Csmox1uEmAWTxPNFcXY6ngV5cifnOALdV5FYlTYmYlAXYuJmZ6hB8oqxQtzRu9AGG8R/VeoE+bPNYhDF50KwIrBGTtw0BnevXyw==
    storage-key: AgAW0fj1GovsymZmysKqeTO/nevZVM0eJEE9dqxOcWzXKIfN62emIy+0zuyUPZWNj/BtCOFf+qZMKaThpNP9At+wBl0y23xBKuZ+uk3g5BDOQ73hi9HjoS8VqiFzFhOWA1LIdHLvC0loPOKpQ+YcLKR+bNX0yn++iIfVTZbNV/DG0VtllSmKfnX0IV2Neihzzvet7MiDNeHx6WY+sN+Ai5Z6SgpHn7ZfdnNXgRjA8O078BDg0RLD+0MnGNsijVZoyw9OP7aWiVm2SnTmb54gUjCGzOz2MSK/mAwsGDxE/WoRslEdYQ8yE/UeWj0HGV3k/K1krznfmOszlS4ZC+075G0Cp1ZS7sILDOprOIO6EubqI8ZdO9g3y9SVSoDeFeptk3AoIu6SZorBcg0kC3CW21+AgPTDe6G0e1cDwNC51O0Wmu77sk93MhM0JkbtI2zJ2/iQo2LXvaaAHem5qQ8w+sBU3gd2h1Lg4P+Rhsyt1xkWjgpmiCkXVfmfzoxJi+Wm4/h7q6QkVl1cFje/Ph6tMYs3AeL3nqeqwxjko2BxZyVWBtYupzA2CaCDybt36R1MTlY6JEoMN/3ZlihM0WkWWITk14bZl2yRhiqQHxqWFxDMgC0WnKG6QTMiF+IDxqnJXRdNiJqbVS2AgQUejttavF6bWyj6FnnXCwAhAyAtc+q2KoWS40fKWRrP9+QWCE2vj2hFzB0PvRoYlYgTT9jpMe61R9crNApBIU3UAci1SySYJBFY3/mYstvFwX1D1nl8ossuWUEDYkgDn/PLmozZlkkofAkEU0S1YOFCug8zHOJuGjHkFVescL8Q
  template:
    metadata:
      creationTimestamp: null
      name: causes-db-backup-azure-secrets
      namespace: now-u
